version: '3.9'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend
    ports:
      - 5173:5173
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app/apps/frontend
    env_file:
      - ./apps/frontend/.env

  api-server:
    build: 
      context: .
      dockerfile: Dockerfile
      target: api-server
    ports:
     - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app/apps/api-server
    env_file:
      - ./apps/api-server/.env
  
  yjs-server:
    build: 
      context: .
      dockerfile: Dockerfile
      target: yjs-server
    ports:
      - "1234:1234"
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app/apps/yjs-server
    env_file:
      - ./apps/yjs-server/.env
    
  
  websocket-server:
    build: 
      context: .
      dockerfile: Dockerfile
      target: websocket-server
    ports:
      - "8080:8080"
    env_file:
      - ./apps/websocket-server/.env
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app/apps/websocket-server
    depends_on:
      - redis
  
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
     - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  redis-data: